export const JOB_INFO: { [key: string]: { mainStat: string; attType: string } } = {
    "히어로": { mainStat: "STR", attType: "attack_power" },
    "팔라딘": { mainStat: "STR", attType: "attack_power" },
    "다크나이트": { mainStat: "STR", attType: "attack_power" },
    "아크메이지(불,독)": { mainStat: "INT", attType: "magic_power" },
    "아크메이지(썬,콜)": { mainStat: "INT", attType: "magic_power" },
    "비숍": { mainStat: "INT", attType: "magic_power" },
    "보우마스터": { mainStat: "DEX", attType: "attack_power" },
    "신궁": { mainStat: "DEX", attType: "attack_power" },
    "패스파인더": { mainStat: "DEX", attType: "attack_power" },
    "나이트로드": { mainStat: "LUK", attType: "attack_power" },
    "섀도어": { mainStat: "LUK", attType: "attack_power" },
    "듀얼블레이드": { mainStat: "LUK", attType: "attack_power" },
    "바이퍼": { mainStat: "STR", attType: "attack_power" },
    "캡틴": { mainStat: "DEX", attType: "attack_power" },
    "캐논슈터": { mainStat: "STR", attType: "attack_power" },
    "미하일": { mainStat: "STR", attType: "attack_power" },
    "소울마스터": { mainStat: "STR", attType: "attack_power" },
    "플레임위자드": { mainStat: "INT", attType: "magic_power" },
    "윈드브레이커": { mainStat: "DEX", attType: "attack_power" },
    "나이트워커": { mainStat: "LUK", attType: "attack_power" },
    "스트라이커": { mainStat: "STR", attType: "attack_power" },
    "아란": { mainStat: "STR", attType: "attack_power" },
    "에반": { mainStat: "INT", attType: "magic_power" },
    "루미너스": { mainStat: "INT", attType: "magic_power" },
    "메르세데스": { mainStat: "DEX", attType: "attack_power" },
    "팬텀": { mainStat: "LUK", attType: "attack_power" },
    "은월": { mainStat: "STR", attType: "attack_power" },
    "블래스터": { mainStat: "STR", attType: "attack_power" },
    "배틀메이지": { mainStat: "INT", attType: "magic_power" },
    "와일드헌터": { mainStat: "DEX", attType: "attack_power" },
    "메카닉": { mainStat: "DEX", attType: "attack_power" },
    "제논": { mainStat: "STR", attType: "attack_power" },
    "데몬슬레이어": { mainStat: "STR", attType: "attack_power" },
    "데몬어벤져": { mainStat: "HP", attType: "attack_power" },
    "카이저": { mainStat: "STR", attType: "attack_power" },
    "엔젤릭버스터": { mainStat: "DEX", attType: "attack_power" },
    "카데나": { mainStat: "LUK", attType: "attack_power" },
    "카인": { mainStat: "DEX", attType: "attack_power" },
    "일리움": { mainStat: "INT", attType: "magic_power" },
    "아크": { mainStat: "STR", attType: "attack_power" },
    "아델": { mainStat: "STR", attType: "attack_power" },
    "호영": { mainStat: "LUK", attType: "attack_power" },
    "라라": { mainStat: "INT", attType: "magic_power" },
    "키네시스": { mainStat: "INT", attType: "magic_power" },
    "제로": { mainStat: "STR", attType: "attack_power" },
    "칼리": { mainStat: "LUK", attType: "attack_power" },
    "비스트테이머": { mainStat: "INT", attType: "magic_power" },
    "린": { mainStat: "INT", attType: "magic_power" },
};

export const getJobInfo = (jobName: string) => {
    return JOB_INFO[jobName] || { mainStat: "STR", attType: "attack_power" };
};
