// ================================================================
// 에픽 등급 - 무기 (120~200) 잠재능력 옵션
// ================================================================

import { PotentialOptionPool } from './types';

export const EPIC_WEAPON_120_200: PotentialOptionPool[] = [
    // 첫 번째 줄
    {
        potential_grade: '에픽',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 1,
        options: [
            { option_name: 'STR +6%', probability: 10.8696 },
            { option_name: 'DEX +6%', probability: 10.8696 },
            { option_name: 'INT +6%', probability: 10.8696 },
            { option_name: 'LUK +6%', probability: 10.8696 },
            { option_name: '최대 HP +6%', probability: 10.8696 },
            { option_name: '최대 MP +6%', probability: 10.8696 },
            { option_name: '공격력 +6%', probability: 4.3478 },
            { option_name: '마력 +6%', probability: 4.3478 },
            { option_name: '크리티컬 확률 +8%', probability: 4.3478 },
            { option_name: '데미지 +6%', probability: 4.3478 },
            { option_name: '올스탯 +3%', probability: 4.3478 },
            { option_name: '공격 시 20% 확률로 360의 HP 회복', probability: 4.3478 },
            { option_name: '공격 시 20% 확률로 180의 MP 회복', probability: 4.3478 },
            { option_name: '몬스터 방어율 무시 +15%', probability: 4.3478 },
        ]
    },
    // 두 번째 줄
    {
        potential_grade: '에픽',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 2,
        options: [
            { option_name: 'STR +12', probability: 4.8980 },
            { option_name: 'DEX +12', probability: 4.8980 },
            { option_name: 'INT +12', probability: 4.8980 },
            { option_name: 'LUK +12', probability: 4.8980 },
            { option_name: '최대 HP +120', probability: 4.8980 },
            { option_name: '최대 MP +120', probability: 4.8980 },
            { option_name: '공격력 +12', probability: 3.2653 },
            { option_name: '마력 +12', probability: 3.2653 },
            { option_name: 'STR +3%', probability: 4.8980 },
            { option_name: 'DEX +3%', probability: 4.8980 },
            { option_name: 'INT +3%', probability: 4.8980 },
            { option_name: 'LUK +3%', probability: 4.8980 },
            { option_name: '공격력 +3%', probability: 1.6327 },
            { option_name: '마력 +3%', probability: 1.6327 },
            { option_name: '크리티컬 확률 +4%', probability: 1.6327 },
            { option_name: '데미지 +3%', probability: 1.6327 },
            { option_name: '올스탯 +5', probability: 3.2653 },
            { option_name: '공격 시 20% 확률로 240의 HP 회복', probability: 1.6327 },
            { option_name: '공격 시 20% 확률로 120의 MP 회복', probability: 1.6327 },
            { option_name: '공격 시 20% 확률로 6레벨 중독효과 적용', probability: 1.6327 },
            { option_name: '공격 시 10% 확률로 2레벨 기절효과 적용', probability: 1.6327 },
            { option_name: '공격 시 20% 확률로 2레벨 슬로우효과 적용', probability: 1.6327 },
            { option_name: '공격 시 20% 확률로 3레벨 암흑효과 적용', probability: 1.6327 },
            { option_name: '공격 시 10% 확률로 2레벨 빙결효과 적용', probability: 1.6327 },
            { option_name: '공격 시 10% 확률로 2레벨 봉인효과 적용', probability: 1.6327 },
            { option_name: '몬스터 방어율 무시 +15%', probability: 1.6327 },
            { option_name: 'STR +6%', probability: 2.1739 },
            { option_name: 'DEX +6%', probability: 2.1739 },
            { option_name: 'INT +6%', probability: 2.1739 },
            { option_name: 'LUK +6%', probability: 2.1739 },
            { option_name: '최대 HP +6%', probability: 2.1739 },
            { option_name: '최대 MP +6%', probability: 2.1739 },
            { option_name: '공격력 +6%', probability: 0.8696 },
            { option_name: '마력 +6%', probability: 0.8696 },
            { option_name: '크리티컬 확률 +8%', probability: 0.8696 },
            { option_name: '데미지 +6%', probability: 0.8696 },
            { option_name: '올스탯 +3%', probability: 0.8696 },
            { option_name: '공격 시 20% 확률로 360의 HP 회복', probability: 0.8696 },
            { option_name: '공격 시 20% 확률로 180의 MP 회복', probability: 0.8696 },
            { option_name: '몬스터 방어율 무시 +15%', probability: 0.8696 },
        ]
    },
    // 세 번째 줄
    {
        potential_grade: '에픽',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 3,
        options: [
            { option_name: 'STR +12', probability: 5.8163 },
            { option_name: 'DEX +12', probability: 5.8163 },
            { option_name: 'INT +12', probability: 5.8163 },
            { option_name: 'LUK +12', probability: 5.8163 },
            { option_name: '최대 HP +120', probability: 5.8163 },
            { option_name: '최대 MP +120', probability: 5.8163 },
            { option_name: '공격력 +12', probability: 3.8776 },
            { option_name: '마력 +12', probability: 3.8776 },
            { option_name: 'STR +3%', probability: 5.8163 },
            { option_name: 'DEX +3%', probability: 5.8163 },
            { option_name: 'INT +3%', probability: 5.8163 },
            { option_name: 'LUK +3%', probability: 5.8163 },
            { option_name: '공격력 +3%', probability: 1.9388 },
            { option_name: '마력 +3%', probability: 1.9388 },
            { option_name: '크리티컬 확률 +4%', probability: 1.9388 },
            { option_name: '데미지 +3%', probability: 1.9388 },
            { option_name: '올스탯 +5', probability: 3.8776 },
            { option_name: '공격 시 20% 확률로 240의 HP 회복', probability: 1.9388 },
            { option_name: '공격 시 20% 확률로 120의 MP 회복', probability: 1.9388 },
            { option_name: '공격 시 20% 확률로 6레벨 중독효과 적용', probability: 1.9388 },
            { option_name: '공격 시 10% 확률로 2레벨 기절효과 적용', probability: 1.9388 },
            { option_name: '공격 시 20% 확률로 2레벨 슬로우효과 적용', probability: 1.9388 },
            { option_name: '공격 시 20% 확률로 3레벨 암흑효과 적용', probability: 1.9388 },
            { option_name: '공격 시 10% 확률로 2레벨 빙결효과 적용', probability: 1.9388 },
            { option_name: '공격 시 10% 확률로 2레벨 봉인효과 적용', probability: 1.9388 },
            { option_name: '몬스터 방어율 무시 +15%', probability: 1.9388 },
            { option_name: 'STR +6%', probability: 0.5435 },
            { option_name: 'DEX +6%', probability: 0.5435 },
            { option_name: 'INT +6%', probability: 0.5435 },
            { option_name: 'LUK +6%', probability: 0.5435 },
            { option_name: '최대 HP +6%', probability: 0.5435 },
            { option_name: '최대 MP +6%', probability: 0.5435 },
            { option_name: '공격력 +6%', probability: 0.2174 },
            { option_name: '마력 +6%', probability: 0.2174 },
            { option_name: '크리티컬 확률 +8%', probability: 0.2174 },
            { option_name: '데미지 +6%', probability: 0.2174 },
            { option_name: '올스탯 +3%', probability: 0.2174 },
            { option_name: '공격 시 20% 확률로 360의 HP 회복', probability: 0.2174 },
            { option_name: '공격 시 20% 확률로 180의 MP 회복', probability: 0.2174 },
            { option_name: '몬스터 방어율 무시 +15%', probability: 0.2174 },
        ]
    }
];
