export const TIERS = [
  { name: '브론즈', points: 5000, reqBoss: null, rewards: '챌린저스 월드 시즌4 브론즈 훈장 교환권, 솔 에르다 조각 100개, 솔 에르다 3개, 챌린저스 휘장로이드 교환권, 챌린저스 월드 시즌4 브론즈 모자, 챌린저스 3레벨 특수 스킬 반지 선택권' },
  { name: '실버', points: 10000, reqBoss: null, rewards: '챌린저스 월드 시즌4 실버 훈장 교환권, 챌린저스 4레벨 특수 스킬 반지 선택권, 솔 에르다 조각 100개, 솔 에르다 3개, 챌린저스 월드 시즌4 실버 모자' },
  { name: '골드', points: 15000, reqBoss: null, rewards: '챌린저스 월드 시즌4 골드 훈장 교환권, 솔 에르다 조각 100개, 솔 에르다 3개, 페어리 하트, 챌린저스 월드 시즌4 골드 모자' },
  { name: '플래티넘', points: 20000, reqBoss: null, rewards: '챌린저스 월드 시즌4 플래티넘 훈장 교환권, 솔 에르다 조각 300개, 솔 에르다 5개, 챌린저스 월드 시즌4 플래티넘 모자' },
  { name: '에메랄드', points: 30000, reqBoss: null, rewards: '챌린저스 월드 시즌4 에메랄드 훈장 교환권, 200레벨 달성의 비약 20개, 카르마 레전드리 잠재능력 부여 스크롤 100% (200제), 카르마 블랙 큐브 30개, 챌린저스 월드 시즌4 에메랄드 모자' },
  { name: '사파이어', points: 40000, reqBoss: null, rewards: '챌린저스 월드 시즌4 사파이어 훈장 교환권, 카르마 에디셔널 유니크 잠재능력 부여 스크롤 100% (200제), 카르마 레전드리 잠재능력 부여 스크롤 100% (200제), 챌린저스 월드 시즌4 사파이어 모자' },
  { name: '다이아몬드', points: 50000, reqBoss: null, rewards: '챌린저스 월드 시즌4 다이아몬드 훈장 교환권, 카르마 화이트 에디셔널 큐브 30개, 하트 업그레이드 모듈: 플라즈마, 챌린저스 월드 시즌4 다이아몬드 모자' },
  { name: '마스터', points: 70000, reqBoss: '메이린(노멀)', rewards: '챌린저스 월드 시즌4 마스터 훈장 교환권, 카르마 블랙 큐브 30개, 카르마 화이트 에디셔널 큐브 30개, 메멘토 방어구 스타포스 18성 강화권 (200제) 3개, 250레벨 달성의 비약 1개, 챌린저스 월드 시즌4 마스터 모자' },
  { name: '챌린저', points: 90000, reqBoss: '메이린(하드)', rewards: '챌린저스 월드 시즌4 챌린저 훈장 교환권, 챌린저스 월드 시즌4 챌린저 가구 교환권, 솔 야누스 스킬 강화권 (20레벨), 챌린저스 월드 시즌4 챌린저 모자' },
  { name: '슈퍼챌린저', points: 90000, reqBoss: '메이린(하드)', rewards: '챌린저스 월드 시즌4 슈퍼챌린저 훈장 교환권, 챌린저스 월드 시즌4 슈퍼챌린저 가구 교환권, 솔 야누스 스킬 강화권 (20레벨), 챌린저스 월드 시즌4 슈퍼챌린저 모자' }
];

export const LEVEL_MISSIONS = [
  { level: 260, type: 'achieve', points: 3000, coins: 3000 },
  { level: 261, type: 'perLevel', points: 300, coins: 300 },
  { level: 262, type: 'perLevel', points: 300, coins: 300 },
  { level: 263, type: 'perLevel', points: 300, coins: 300 },
  { level: 264, type: 'perLevel', points: 300, coins: 300 },
  { level: 265, type: 'perLevel', points: 300, coins: 300 },
  { level: 266, type: 'perLevel', points: 300, coins: 300 },
  { level: 267, type: 'perLevel', points: 300, coins: 300 },
  { level: 268, type: 'perLevel', points: 300, coins: 300 },
  { level: 269, type: 'perLevel', points: 300, coins: 300 },
  { level: 270, type: 'perLevel', points: 700, coins: 600 },
  { level: 271, type: 'perLevel', points: 700, coins: 600 },
  { level: 272, type: 'perLevel', points: 700, coins: 600 },
  { level: 273, type: 'perLevel', points: 700, coins: 600 },
  { level: 274, type: 'perLevel', points: 700, coins: 600 },
  { level: 275, type: 'perLevel', points: 1000, coins: 900 },
  { level: 276, type: 'perLevel', points: 1000, coins: 900 },
  { level: 277, type: 'perLevel', points: 1000, coins: 900 },
  { level: 278, type: 'perLevel', points: 1000, coins: 900 },
  { level: 279, type: 'perLevel', points: 1000, coins: 900 },
  { level: 280, type: 'perLevel', points: 1500, coins: 1200 },
  { level: 281, type: 'perLevel', points: 1500, coins: 1200 },
  { level: 282, type: 'perLevel', points: 1500, coins: 1200 },
  { level: 283, type: 'perLevel', points: 1500, coins: 1200 },
  { level: 284, type: 'perLevel', points: 1500, coins: 1200 },
  { level: 285, type: 'perLevel', points: 2000, coins: 1500 },
  { level: 286, type: 'perLevel', points: 2000, coins: 1500 },
  { level: 287, type: 'perLevel', points: 2000, coins: 1500 },
  { level: 288, type: 'perLevel', points: 2000, coins: 1500 },
  { level: 289, type: 'perLevel', points: 2000, coins: 1500 },
  { level: 290, type: 'achieve', points: 5000, coins: 2500 },
];

export const BOSS_MISSIONS = [
  { id: 'zakum_chaos', name: '자쿰', difficulty: '카오스', points: 100, coins: 100, advancedCoins: 0, group: 'zakum', level: 1 },
  { id: 'pierre_chaos', name: '피에르', difficulty: '카오스', points: 200, coins: 100, advancedCoins: 0, group: 'pierre', level: 1 },
  { id: 'banban_chaos', name: '반반', difficulty: '카오스', points: 200, coins: 100, advancedCoins: 0, group: 'banban', level: 1 },
  { id: 'bloodyqueen_chaos', name: '블러디퀸', difficulty: '카오스', points: 200, coins: 200, advancedCoins: 0, group: 'bloodyqueen', level: 1 },
  { id: 'magnus_hard', name: '매그너스', difficulty: '하드', points: 250, coins: 200, advancedCoins: 0, group: 'magnus', level: 1 },
  { id: 'vellum_chaos', name: '벨룸', difficulty: '카오스', points: 250, coins: 200, advancedCoins: 0, group: 'vellum', level: 1 },
  { id: 'papulatus_chaos', name: '파풀라투스', difficulty: '카오스', points: 300, coins: 200, advancedCoins: 0, group: 'papulatus', level: 1 },
  { id: 'suu_normal', name: '스우', difficulty: '노멀', points: 400, coins: 200, advancedCoins: 0, group: 'suu', level: 1 },
  { id: 'suu_hard', name: '스우', difficulty: '하드', points: 1500, coins: 400, advancedCoins: 0, group: 'suu', level: 2 },
  { id: 'demian_normal', name: '데미안', difficulty: '노멀', points: 400, coins: 200, advancedCoins: 0, group: 'demian', level: 1 },
  { id: 'demian_hard', name: '데미안', difficulty: '하드', points: 1500, coins: 400, advancedCoins: 0, group: 'demian', level: 2 },
  { id: 'slime_normal', name: '가디언 엔젤 슬라임', difficulty: '노멀', points: 500, coins: 200, advancedCoins: 0, group: 'slime', level: 1 },
  { id: 'slime_chaos', name: '가디언 엔젤 슬라임', difficulty: '카오스', points: 2500, coins: 600, advancedCoins: 0, group: 'slime', level: 2 },
  { id: 'lucid_easy', name: '루시드', difficulty: '이지', points: 500, coins: 200, advancedCoins: 0, group: 'lucid', level: 1 },
  { id: 'lucid_normal', name: '루시드', difficulty: '노멀', points: 1000, coins: 300, advancedCoins: 0, group: 'lucid', level: 2 },
  { id: 'lucid_hard', name: '루시드', difficulty: '하드', points: 2000, coins: 600, advancedCoins: 0, group: 'lucid', level: 3 },
  { id: 'will_easy', name: '윌', difficulty: '이지', points: 500, coins: 200, advancedCoins: 0, group: 'will', level: 1 },
  { id: 'will_normal', name: '윌', difficulty: '노멀', points: 1000, coins: 300, advancedCoins: 0, group: 'will', level: 2 },
  { id: 'will_hard', name: '윌', difficulty: '하드', points: 2500, coins: 600, advancedCoins: 0, group: 'will', level: 3 },
  { id: 'kai_normal', name: '카이', difficulty: '노멀', points: 1000, coins: 300, advancedCoins: 0, group: 'kai', level: 1 },
  { id: 'dusk_normal', name: '더스크', difficulty: '노멀', points: 1000, coins: 300, advancedCoins: 0, group: 'dusk', level: 1 },
  { id: 'dusk_chaos', name: '더스크', difficulty: '카오스', points: 2500, coins: 600, advancedCoins: 0, group: 'dusk', level: 2 },
  { id: 'hilla_normal', name: '진 힐라', difficulty: '노멀', points: 2000, coins: 600, advancedCoins: 0, group: 'hilla', level: 1 },
  { id: 'hilla_hard', name: '진 힐라', difficulty: '하드', points: 3000, coins: 1000, advancedCoins: 0, group: 'hilla', level: 2 },
  { id: 'dunkel_normal', name: '듄켈', difficulty: '노멀', points: 1000, coins: 300, advancedCoins: 0, group: 'dunkel', level: 1 },
  { id: 'dunkel_hard', name: '듄켈', difficulty: '하드', points: 3000, coins: 1000, advancedCoins: 0, group: 'dunkel', level: 2 },
  { id: 'blackmage_hard', name: '검은 마법사', difficulty: '하드', points: 6000, coins: 1400, advancedCoins: 20, group: 'blackmage', level: 1 },
  { id: 'seren_normal', name: '선택받은 세렌', difficulty: '노멀', points: 6000, coins: 1400, advancedCoins: 20, group: 'seren', level: 1 },
  { id: 'seren_hard', name: '선택받은 세렌', difficulty: '하드', points: 7000, coins: 2000, advancedCoins: 30, group: 'seren', level: 2 },
  { id: 'kalos_easy', name: '감시자 칼로스', difficulty: '이지', points: 7000, coins: 2000, advancedCoins: 30, group: 'kalos', level: 1 },
  { id: 'kalos_normal', name: '감시자 칼로스', difficulty: '노멀', points: 9000, coins: 3000, advancedCoins: 60, group: 'kalos', level: 2 },
  { id: 'daejeok_easy', name: '최초의 대적자', difficulty: '이지', points: 7000, coins: 2000, advancedCoins: 30, group: 'daejeok', level: 1 },
  { id: 'daejeok_normal', name: '최초의 대적자', difficulty: '노멀', points: 9000, coins: 3000, advancedCoins: 60, group: 'daejeok', level: 2 },
  { id: 'kaling_easy', name: '카링', difficulty: '이지', points: 9000, coins: 3000, advancedCoins: 60, group: 'kaling', level: 1 },
  { id: 'meilin_normal', name: '메이린', difficulty: '노멀', points: 5000, coins: 1200, advancedCoins: 10, group: 'meilin', level: 1 },
  { id: 'meilin_hard', name: '메이린', difficulty: '하드', points: 9000, coins: 3000, advancedCoins: 60, group: 'meilin', level: 2 },
];

export const SEASON_MISSIONS = [
  { id: 'ability_1', category: '어빌리티', desc: '어빌리티 유니크 등급 달성', coins: 100 },
  { id: 'ability_2', category: '어빌리티', desc: '어빌리티 레전드리 등급 달성', coins: 300 },
  { id: 'ability_3', category: '어빌리티', desc: '레전드리 어빌리티 획득 (특정 옵션)', coins: 500 },
  
  { id: 'arcane_1', category: '아케인 포스', desc: '아케인 심볼 60레벨', coins: 100 },
  { id: 'arcane_2', category: '아케인 포스', desc: '아케인 심볼 80레벨', coins: 300 },
  { id: 'arcane_3', category: '아케인 포스', desc: '아케인 심볼 100레벨', coins: 500 },
  { id: 'arcane_4', category: '아케인 포스', desc: '아케인 심볼 120레벨', coins: 1000 },
  
  { id: 'authentic_1', category: '어센틱 포스', desc: '어센틱 심볼 20레벨', coins: 100 },
  { id: 'authentic_2', category: '어센틱 포스', desc: '어센틱 심볼 25레벨', coins: 100 },
  { id: 'authentic_3', category: '어센틱 포스', desc: '어센틱 심볼 30레벨', coins: 300 },
  { id: 'authentic_4', category: '어센틱 포스', desc: '어센틱 심볼 35레벨', coins: 300 },
  { id: 'authentic_5', category: '어센틱 포스', desc: '어센틱 심볼 40레벨', coins: 500 },
  
  { id: 'equip_1', category: '장비', desc: '잠재 능력 레전드리 엠블렘', coins: 1000 },
  { id: 'equip_2', category: '장비', desc: '잠재 능력 레전드리 보조 무기', coins: 1000 },
  { id: 'equip_3', category: '장비', desc: '에디 유니크 이상 엠블렘', coins: 500 },
  { id: 'equip_4', category: '장비', desc: '에디 유니크 이상 보조 무기', coins: 500 },
  
  { id: 'skill5_1', category: '5차 스킬', desc: '직업 코어 2개 30레벨', coins: 100 },
  { id: 'skill5_2', category: '5차 스킬', desc: '직업 코어 4개 30레벨', coins: 300 },
  { id: 'skill5_3', category: '5차 스킬', desc: '강화 코어 2개 60레벨', coins: 100 },
  { id: 'skill5_4', category: '5차 스킬', desc: '강화 코어 4개 60레벨', coins: 300 },
  
  { id: 'hexa_stat_1', category: 'HEXA 스탯', desc: 'HEXA 스탯 I 활성화', coins: 300 },
  
  { id: 'hexa_skill_1', category: 'HEXA 스킬', desc: '솔 에르다 조각 300개 사용', coins: 100 },
  { id: 'hexa_skill_2', category: 'HEXA 스킬', desc: '솔 에르다 조각 600개 사용', coins: 300 },
  { id: 'hexa_skill_3', category: 'HEXA 스킬', desc: '솔 에르다 조각 900개 사용', coins: 300 },
  { id: 'hexa_skill_4', category: 'HEXA 스킬', desc: '솔 에르다 조각 1,200개 사용', coins: 500 },
  { id: 'hexa_skill_5', category: 'HEXA 스킬', desc: '솔 에르다 조각 1,500개 사용', coins: 500 },
  { id: 'hexa_skill_6', category: 'HEXA 스킬', desc: '솔 에르다 조각 1,800개 사용', coins: 1000 },
  
  { id: 'power_1', category: '전투력', desc: '전투력 1,000만 달성', coins: 100 },
  { id: 'power_2', category: '전투력', desc: '전투력 3,000만 달성', coins: 300 },
  { id: 'power_3', category: '전투력', desc: '전투력 5,000만 달성', coins: 300 },
  { id: 'power_4', category: '전투력', desc: '전투력 7,000만 달성', coins: 500 },
  { id: 'power_5', category: '전투력', desc: '전투력 1억 달성', coins: 1000 },
  
  { id: 'genesis_1', category: '무기 해방', desc: '제네시스 1차 해방하기', coins: 500 },
  { id: 'genesis_2', category: '무기 해방', desc: '제네시스 2차 해방하기', coins: 1000 },
];

export const WEEKLY_COINS = 1500;
export const MAX_WEEKS = 13; // 6/18 ~ 9/17

export const NORMAL_SHOP_ITEMS = [
  { id: 'ns_01', name: '블랙 보조 무기 상자', price: 100, maxQty: 1 },
  { id: 'ns_02', name: '스페셜 소울 인챈터', price: 100, maxQty: 3 },
  { id: 'ns_03', name: '경험치 3배 쿠폰 (30분)', price: 100, maxQty: 91, isWeekly: true, limitPerWeek: 7 },
  { id: 'ns_04', name: 'VIP 버프 (경험치)', price: 30, maxQty: 9999 },
  { id: 'ns_05', name: 'VIP 버프 (능력치)', price: 30, maxQty: 9999 },
  { id: 'ns_06', name: '카르마 검은 환생의 불꽃', price: 50, maxQty: 1000 },
  { id: 'ns_07', name: '솔 에르다 조각', price: 40, maxQty: 500 },
  { id: 'ns_08', name: '솔 에르다', price: 2000, maxQty: 5 },
  { id: 'ns_09', name: '메멘토 골드 큐브 (200제)', price: 100, maxQty: 50 },
  { id: 'ns_10', name: '메멘토 실버 큐브 (200제)', price: 50, maxQty: 500 },
  { id: 'ns_11', name: '카르마 브론즈 에디셔널 큐브', price: 20, maxQty: 1000 },
  { id: 'ns_12', name: '펫장비 주문서 선택권', price: 500, maxQty: 100 },
  { id: 'ns_13', name: '에픽 잠재능력 부여 스크롤 100%', price: 150, maxQty: 30 },
  { id: 'ns_14', name: '에디셔널 잠재능력 부여 스크롤 100%', price: 150, maxQty: 30 },
  { id: 'ns_15', name: '카르마 프리미엄 펫장비 주문서 선택권', price: 1000, maxQty: 10 },
  { id: 'ns_16', name: '이노센트 주문서 100%', price: 50, maxQty: 10 },
  { id: 'ns_17', name: '순백의 주문서 100%', price: 100, maxQty: 10 },
  { id: 'ns_18', name: '카르마 스타포스 17성 강화권 (160제)', price: 3000, maxQty: 3 },
  { id: 'ns_19', name: '카르마 프리미엄 악세서리 주문서 선택권', price: 1000, maxQty: 10 },
  { id: 'ns_20', name: '주문의 흔적 (1,000개)', price: 100, maxQty: 9999 },
];

export const SPECIAL_SHOP_ITEMS = [
  { id: 'ss_01', name: '솔 에르다 조각 (10개 묶음)', price: 1, maxQty: 10 },
  { id: 'ss_02', name: '카르마 심연의 환생의 불꽃', price: 1, maxQty: 250 },
  { id: 'ss_03', name: '솔 에르다', price: 3, maxQty: 20 },
  { id: 'ss_04', name: '카르마 블랙 큐브', price: 1, maxQty: 20 },
  { id: 'ss_05', name: '카르마 화이트 에디셔널 큐브', price: 2, maxQty: 20 },
];
