export interface BlogPost {
    slug: string;
    title: string;
    description: string;
    category: string;
    date: string;
    readTime: string;
    thumbnail: string;
    featured?: boolean;
    targetDate?: string; // 적용 예정일 (옵션)
}

export const blogPosts: BlogPost[] = [
    // 긴급! 이벤트 마감 안내 (1/14)
    {
        slug: 'event-ending-jan-14-2026',
        title: '🚨 내일(1/14 수요일) 밤 11시 59분 마감! 놓치면 안 되는 이벤트 총정리',
        description: '극한 성장의 비약 3개부터 KINETIC 이벤트까지! 1월 14일 종료 이벤트 완벽 정리 + 챌린저스 월드 시즌 3 리프 안내',
        category: '이벤트 가이드',
        date: '2026년 1월 13일',
        readTime: '8분',
        thumbnail: '🚨',
        featured: true,
    },
    // 최신 업데이트 - 테스트월드 스킬 밸런스
    {
        slug: 'testworld-skill-balance-1-8-2026',
        title: '⚔️ 테스트월드 클라이언트 1.2.197 릴리즈 - 스킬 조정 총정리',
        description: '2026년 1월 15일 본섭 적용 예정! 전 직업 스킬 밸런스 패치 상세 분석. 다크나이트 신규 스킬 리인카네이션 알터 추가!',
        category: '업데이트 소식',
        date: '2026년 1월 8일',
        readTime: '15분',
        thumbnail: '⚔️',
        featured: false,
        targetDate: '2026년 1월 15일',
    },
    // 신규 시스템 - 솔 헤카테
    {
        slug: 'testworld-sol-hecate',
        title: '🌑 신규 6차 공용 코어 솔 헤카테 완벽 분석 - 성장형 소환수',
        description: '전직업 공용 성장형 소환수 솔 헤카테 출시! 레벨별 해금 스킬(스틱스, 카론, 플레게톤)과 스킬 매니지먼트 시스템 상세 분석.',
        category: '업데이트 소식',
        date: '2026년 1월 9일',
        readTime: '15분',
        thumbnail: '🌑',
        featured: true,
        targetDate: '2026년 1월 15일',
    },
    // 신규 시스템 - 아스트라 보조무기
    {
        slug: 'testworld-astra-secondary-weapon',
        title: '🛡️ 아스트라 보조무기 완벽 가이드 - 획득부터 전승까지',
        description: '그란디스의 힘이 담긴 새로운 보조무기! 격전의 흔적, 에리온의 조각 파밍 방법과 직업별 전승 규칙까지 완벽 정리.',
        category: '업데이트 소식',
        date: '2026년 1월 9일',
        readTime: '20분',
        thumbnail: '🛡️',
        featured: true,
        targetDate: '2026년 1월 15일',
    },
    // 신규 보스 & 대규모 업데이트
    {
        slug: 'testworld-update-1-2-197',
        title: '✨ 테스트월드 1.2.197 릴리즈 총정리 - 신규 보스 & 대규모 업데이트',
        description: '2026년 1월 15일 본섭 적용 예정! 찬란한 흉성, 버닝 익스프레스, 모멘텀 패스 등 주요 업데이트 내용 총정리.',
        category: '업데이트 소식',
        date: '2026년 1월 9일',
        readTime: '10분',
        thumbnail: '✨',
        featured: false,
        targetDate: '2026년 1월 15일',
    },

    // 최신 공지 - 감사의 마음
    {
        slug: 'thank-you-gift-2026',
        title: '🎁 용사님들께 드리는 감사의 마음 | 극한 성장의 비약 무료 지급 (1/14까지)',
        description: '넥슨 공식 감사 선물! 극한 성장의 비약(200~249) 3개를 무료로 받으세요. 버닝 캐릭터도 사용 가능!',
        category: '이벤트 가이드',
        date: '2026년 1월 6일',
        readTime: '3분',
        thumbnail: '🎁',
        featured: false,
    },
    // 긴급 공지 - CROWN 쇼케이스 (12/31 마감)
    {
        slug: 'maple-npc-rewards-2025',
        title: '⏰ 놓치지 마세요! 메이플 운영자 NPC 보상 마감 임박 (12/31까지)',
        description: 'CROWN 쇼케이스 선물과 극한 성장의 비약을 받을 수 있는 마지막 기회! 12월 31일까지 꼭 받으세요!',
        category: '이벤트 가이드',
        date: '2025년 12월 29일',
        readTime: '3분',
        thumbnail: '🎁',
        featured: false,
    },
    // 육성 가이드
    {
        slug: 'link-union-guide',
        title: '🌟 링크 & 유니온 육성 가이드 - 효율적인 캐릭터 육성 순서 완벽 정리',
        description: '경험치 링크 vs 딜 링크, 140레벨 vs 200레벨 목표, 보스용 엔드급 링크 세팅까지! 맨땅 헤딩 없이 효율적으로 링크와 유니온을 완성하는 로드맵을 제시합니다.',
        category: '육성 가이드',
        date: '2026년 1월 7일',
        readTime: '12분',
        thumbnail: '🌟',
        featured: true,
    },
    {
        slug: 'hyperburning-jobs-2025',
        title: '🎬 유튜버 6명이 입 모아 외친 "그 직업". 2025 겨울 하이퍼버닝 추천 직업 통합 분석 (종결판)',
        description: '메친놈, 슈크림메이플, 물다이아, 페이지, 글자네 등 유튜버 6명의 분석 종합! 12월 18일 챌린저스 월드 시즌 3, 어떤 직업을 키워야 할까?',
        category: '육성 가이드',
        date: '2025년 12월 11일',
        readTime: '15분',
        thumbnail: '🔥',
        featured: false,
    },
    {
        slug: 'crown-hyperburning-guide-2025',
        title: '🔥 [2025 메이플] 크라운 하이퍼버닝 & 아이템 버닝 완벽 가이드: "이 순서 모르면 손해 봅니다!"',
        description: '정령의 펜던트 순서, 자석펫 사용법, 딸기 농장 활용까지! 260레벨까지 최단 시간 달성을 위한 필수 체크리스트.',
        category: '육성 가이드',
        date: '2025년 12월 15일',
        readTime: '12분',
        thumbnail: '🔥',
    },
    {
        slug: 'beginner-guide-2025',
        title: '유니온 + 링크부터 200레벨 초고속 육성까지! 완벽 내실 가이드',
        description: '유니온 6000, 링크스킬, 아티팩트까지! 200레벨 4-6시간 달성하는 초고속 육성법과 내실 완벽 가이드.',
        category: '육성 가이드',
        date: '2025년 12월 11일',
        readTime: '20분',
        thumbnail: '⚔️',
    },
    {
        slug: 'hyperburning-jobs-2025-v2',
        title: '🎮 데이터로 증명된 2025 하이퍼버닝 직업 추천 v2.0 (하이브리드 랭킹)',
        description: 'AI, 유튜버, 일반인 인식, 고점 데이터를 모두 섞었다! 4가지 모드로 분석한 가장 완벽한 직업 추천 가이드.',
        category: '육성 가이드',
        date: '2025년 12월 12일',
        readTime: '10분',
        thumbnail: '🚀',
    },
    {
        slug: 'monsterpark-2025',
        title: '🎮 몬스터파크 극한 효율 가이드 - 레벨별 최적 사냥터 완벽 분석',
        description: '260~299 레벨 구간별로 몬스터파크에서 얻을 수 있는 경험치 효율을 완벽하게 정리! 당신의 레벨에 맞는 최적의 사냥터를 찾아보세요.',
        category: '경험치 가이드',
        date: '2025년 12월 13일',
        readTime: '12분',
        thumbnail: '🎯',
    },
    {
        slug: 'free-to-play-guide',
        title: '완전 무자본 200레벨 육성 가이드 - 0메소, 이벤트 없이도 가능!',
        description: '본캐 지원 없이, 이벤트 없이, 0메소로 시작해서 200레벨 달성하는 완벽 퀘스트 육성 가이드. 3시간 30분이면 충분!',
        category: '육성 가이드',
        date: '2025년 12월 11일',
        readTime: '15분',
        thumbnail: '💚',
    },
    // 이벤트 가이드
    {
        slug: 'boss-memory-calculator',
        title: '⚔️ 보스 코인 계산기 & 코인샵 - 보스 선택부터 쇼핑까지!',
        description: '13주 동안의 보스 처치 계획을 세우고, 획득한 환영의 기억으로 바로 쇼핑! 주차별 선택, 자동 합산, 장바구니까지 한 페이지에서 모두 해결하세요.',
        category: '이벤트 가이드',
        date: '2025년 12월 15일',
        readTime: '5분',
        thumbnail: '/images/boss-coin.png',
    },
    {
        slug: 'challengers-world-calculator',
        title: '⚔️ 챌린저스 월드 티어 & 코인 계산기 - 나의 티어를 실시간으로 확인하세요!',
        description: '레벨, 보스, 사냥 미션을 입력하고 챌린저스 포인트와 코인을 자동 계산! 브론즈부터 챌린저까지, 다음 티어까지 얼마나 남았는지 한눈에 확인하세요.',
        category: '이벤트 가이드',
        date: '2025년 12월 15일',
        readTime: '5분',
        thumbnail: '/images/challengers-coin.png',
    },
    {
        slug: 'genesis-liberation-calculator',
        title: '⚔️ 제네시스 무기 해방 계산기 - 챌린저스 시즌3 완벽 가이드',
        description: '주차별 보스 격파 스케줄을 설정하고 17주 안에 제네시스 무기 해방을 완료할 수 있을지 정확하게 계산하세요! 이지부터 하드까지, 월간 보스까지 모두 고려한 정밀 계산.',
        category: '이벤트 가이드',
        date: '2025년 12월 17일',
        readTime: '5분',
        thumbnail: '/images/genesis-weapon.png',
    },
    {
        slug: 'illusion-coin-shop',
        title: '👻 일루전 일반 코인샵 - 환영이 내리는 밤',
        description: '조사 미션으로 획득한 일루전 코인으로 구매 가능한 26가지 아이템(강화/성장)을 확인하고, 필요한 코인을 미리 계획하세요!',
        category: '이벤트 가이드',
        date: '2025년 12월 15일',
        readTime: '3분',
        thumbnail: '/images/illusion-coin.png',
    },

    {
        slug: '/guide/boss-equipment-progression',
        title: '보스 장비 진행도 - 펜살리르부터 22성까지',
        description: '초보자부터 고수까지, 단계별 보스 장비 세팅 가이드. 다음에 뭘 맞춰야 할지 한눈에!',
        category: '장비 가이드',
        date: '2025년 11월 15일',
        readTime: '10분',
        thumbnail: '🛡️',
    },
    {
        slug: '/guide/starforce-efficiency-guide',
        title: '스타포스 효율 가이드 - 언제 강화해야 할까?',
        description: '5/10/15 이벤트, 30% 할인, 스타캐치까지! 스타포스 강화 타이밍과 기댓값을 완벽 분석.',
        category: '장비 가이드',
        date: '2025년 11월 20일',
        readTime: '12분',
        thumbnail: '⭐',
    },
    {
        slug: '/guide/bonus-stat-guide',
        title: '추가옵션 완벽 가이드 - 환생의 불꽃부터 큐브까지',
        description: '장비별 추가옵션 티어와 목표 스탯. 어떤 옵션이 좋은지, 언제 재작해야 하는지 알려드립니다!',
        category: '장비 가이드',
        date: '2025년 11월 28일',
        readTime: '15분',
        thumbnail: '🔥',
    },
    {
        slug: '/guide/cooltime-hat-guide',
        title: '쿨타임 모자 완벽 가이드 - 쿨감의 모든 것',
        description: '쿨타임 감소 모자 획득법과 효율 분석. 내 직업에 쿨감모가 필요한지 알아보세요!',
        category: '장비 가이드',
        date: '2025년 11월 28일',
        readTime: '8분',
        thumbnail: '🎩',
    },
    {
        slug: '/blog/ability-guide',
        title: '직업별 어빌리티 추천 가이드 - 전직업 완벽 정리',
        description: '전직업 보스용 최적 어빌리티. 보공 20%, 상태이상 데미지, 버프 지속시간 조합 가이드!',
        category: '육성 가이드',
        date: '2025년 7월 1일',
        readTime: '10분',
        thumbnail: '🎯',
    },
    {
        slug: '/blog/seed-ring-guide',
        title: '시드링 완벽 가이드 - 획득부터 강화까지',
        description: '시드링 17~22성 강화 전략과 리레벨 옵션 가이드. 내 직업에 맞는 시드링 세팅법!',
        category: '장비 가이드',
        date: '2025년 10월 15일',
        readTime: '12분',
        thumbnail: '💍',
    },
    {
        slug: '/blog/hexa-skills',
        title: '헥사 스킬 완벽 가이드 - 6차 스킬의 모든 것',
        description: '헥사 스킬 시스템 소개부터 강화 전략까지! 솔 에르다, 스킬 선택, 효율적인 육성법 완벽 정리.',
        category: '육성 가이드',
        date: '2025년 9월 1일',
        readTime: '15분',
        thumbnail: '✨',
    },
    {
        slug: '/blog/hexa-skill-priority',
        title: '직업별 헥사 스킬 우선순위 - 뭘 먼저 올려야 할까?',
        description: '전직업 헥사 스킬 우선순위 완벽 정리! 마스터리부터 강화/공용 스킬까지.',
        category: '육성 가이드',
        date: '2025년 9월 10일',
        readTime: '10분',
        thumbnail: '🎯',
    },
    {
        slug: '/blog/hexa-stats-optimization',
        title: '헥사 스탯 최적화 가이드 - 조각 효율의 정석',
        description: '헥사 스탯 레벨별 효율 분석과 최적화 전략. 솔 에르다 조각을 어디에 투자해야 할까?',
        category: '육성 가이드',
        date: '2025년 9월 15일',
        readTime: '12분',
        thumbnail: '📊',
    },
    {
        slug: '/blog/exp-calculator',
        title: '🧮 경험치 계산기 - 사냥/일퀘 레벨업 예측',
        description: '내 레벨에서 목표 레벨까지 얼마나 걸릴까? 사냥터별 효율과 일퀘 경험치를 계산해보세요!',
        category: '경험치 가이드',
        date: '2025년 12월 18일',
        readTime: '5분',
        thumbnail: '📈',
    },
    {
        slug: '/blog/boss-tier-guide',
        title: '보스 난이도 가이드 - 내 전투력으로 어디까지?',
        description: '전투력별 클리어 가능한 보스 완벽 정리. 노말부터 익스트림까지!',
        category: '장비 가이드',
        date: '2025년 11월 1일',
        readTime: '10분',
        thumbnail: '👹',
    },
    {
        slug: '/blog/boss-rewards',
        title: '보스 보상 완벽 정리 - 결정석부터 장비까지',
        description: '보스별 드랍 아이템과 결정석 정산 가이드. 어떤 보스를 돌아야 할지 한눈에!',
        category: '장비 가이드',
        date: '2025년 11월 5일',
        readTime: '8분',
        thumbnail: '💎',
    },
    {
        slug: '/blog/combat-power-tier-system',
        title: '전투력 티어 시스템 - 나는 어디쯤 있을까?',
        description: '브론즈부터 레전드까지! 전투력 구간별 티어와 클리어 가능한 보스 정리.',
        category: '육성 가이드',
        date: '2025년 10월 20일',
        readTime: '7분',
        thumbnail: '⚔️',
    },
    {
        slug: '/blog/about-danpung-i',
        title: '메이플 AI 단풍이 소개 - 당신의 메이플 비서',
        description: '메이플 AI가 무엇인지, 어떻게 활용하는지 완벽 가이드!',
        category: '육성 가이드',
        date: '2025년 10월 1일',
        readTime: '5분',
        thumbnail: '🍁',
    },
    // 메이플 이야기 - 분석/예측/칼럼
    {
        slug: 'crown-winter-showcase-2025',
        title: '👑 메이플스토리 겨울 쇼케이스 "크라운" 완벽 예측: 어셈블을 넘어 정점으로',
        description: '다가오는 12월 13일 오후 4시, 메이플스토리의 운명을 가를 겨울 쇼케이스 "크라운(Crown)"이 개최됩니다. 김창섭 디렉터 체제의 메이플스토리가 이번 겨울, 유저들에게 어떤 왕관을 씌워줄지 기대감이 고조되고 있습니다.',
        category: '메이플 이야기',
        date: '2025년 12월 13일',
        readTime: '15분',
        thumbnail: '👑',
        featured: false,
    },
];
