// ================================================================
// 에디셔널 에픽 등급 - 무기 (120~200) 잠재능력 옵션
// ================================================================

import { AdditionalPotentialOptionPool } from './types';

export const ADDITIONAL_EPIC_WEAPON_120_200: AdditionalPotentialOptionPool[] = [
    // 첫 번째 줄
    {
        potential_grade: '에픽',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 1,
        options: [
            { option_name: '최대 HP +5%', probability: 8.8235 },
            { option_name: '최대 MP +5%', probability: 8.8235 },
            { option_name: '공격력 +6%', probability: 5.8824 },
            { option_name: '마력 +6%', probability: 5.8824 },
            { option_name: '크리티컬 확률 +6%', probability: 2.9412 },
            { option_name: 'STR +6%', probability: 8.8235 },
            { option_name: 'DEX +6%', probability: 8.8235 },
            { option_name: 'INT +6%', probability: 8.8235 },
            { option_name: 'LUK +6%', probability: 8.8235 },
            { option_name: '데미지 +6%', probability: 2.9412 },
            { option_name: '올스탯 +3%', probability: 5.8824 },
            { option_name: '공격 시 3% 확률로 53의 HP 회복', probability: 8.8235 },
            { option_name: '공격 시 3% 확률로 53의 MP 회복', probability: 8.8235 },
            { option_name: '몬스터 방어율 무시 +3%', probability: 5.8824 },
        ]
    },
    // 두 번째 줄
    {
        potential_grade: '에픽',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 2,
        options: [
            { option_name: '최대 HP +100', probability: 5.6022 },
            { option_name: '최대 MP +100', probability: 5.6022 },
            { option_name: '이동속도 +6', probability: 5.6022 },
            { option_name: '점프력 +6', probability: 5.6022 },
            { option_name: '방어력 +100', probability: 5.6022 },
            { option_name: 'STR +12', probability: 5.6022 },
            { option_name: 'DEX +12', probability: 5.6022 },
            { option_name: 'INT +12', probability: 5.6022 },
            { option_name: 'LUK +12', probability: 5.6022 },
            { option_name: '공격력 +12', probability: 3.7348 },
            { option_name: '마력 +12', probability: 3.7348 },
            { option_name: '최대 HP +2%', probability: 3.7348 },
            { option_name: '최대 MP +2%', probability: 3.7348 },
            { option_name: 'STR +3%', probability: 3.7348 },
            { option_name: 'DEX +3%', probability: 3.7348 },
            { option_name: 'INT +3%', probability: 3.7348 },
            { option_name: 'LUK +3%', probability: 3.7348 },
            { option_name: '공격력 +3%', probability: 1.8674 },
            { option_name: '마력 +3%', probability: 1.8674 },
            { option_name: '크리티컬 확률 +4%', probability: 3.7348 },
            { option_name: '데미지 +3%', probability: 1.8674 },
            { option_name: '올스탯 +5', probability: 5.6022 },
            { option_name: '최대 HP +5%', probability: 0.4202 },
            { option_name: '최대 MP +5%', probability: 0.4202 },
            { option_name: '공격력 +6%', probability: 0.2801 },
            { option_name: '마력 +6%', probability: 0.2801 },
            { option_name: '크리티컬 확률 +6%', probability: 0.1401 },
            { option_name: 'STR +6%', probability: 0.4202 },
            { option_name: 'DEX +6%', probability: 0.4202 },
            { option_name: 'INT +6%', probability: 0.4202 },
            { option_name: 'LUK +6%', probability: 0.4202 },
            { option_name: '데미지 +6%', probability: 0.1401 },
            { option_name: '올스탯 +3%', probability: 0.2801 },
            { option_name: '공격 시 3% 확률로 53의 HP 회복', probability: 0.4202 },
            { option_name: '공격 시 3% 확률로 53의 MP 회복', probability: 0.4202 },
            { option_name: '몬스터 방어율 무시 +3%', probability: 0.2801 },
        ]
    },
    // 세 번째 줄
    {
        potential_grade: '에픽',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 3,
        options: [
            { option_name: '최대 HP +100', probability: 5.6022 },
            { option_name: '최대 MP +100', probability: 5.6022 },
            { option_name: '이동속도 +6', probability: 5.6022 },
            { option_name: '점프력 +6', probability: 5.6022 },
            { option_name: '방어력 +100', probability: 5.6022 },
            { option_name: 'STR +12', probability: 5.6022 },
            { option_name: 'DEX +12', probability: 5.6022 },
            { option_name: 'INT +12', probability: 5.6022 },
            { option_name: 'LUK +12', probability: 5.6022 },
            { option_name: '공격력 +12', probability: 3.7348 },
            { option_name: '마력 +12', probability: 3.7348 },
            { option_name: '최대 HP +2%', probability: 3.7348 },
            { option_name: '최대 MP +2%', probability: 3.7348 },
            { option_name: 'STR +3%', probability: 3.7348 },
            { option_name: 'DEX +3%', probability: 3.7348 },
            { option_name: 'INT +3%', probability: 3.7348 },
            { option_name: 'LUK +3%', probability: 3.7348 },
            { option_name: '공격력 +3%', probability: 1.8674 },
            { option_name: '마력 +3%', probability: 1.8674 },
            { option_name: '크리티컬 확률 +4%', probability: 3.7348 },
            { option_name: '데미지 +3%', probability: 1.8674 },
            { option_name: '올스탯 +5', probability: 5.6022 },
            { option_name: '최대 HP +5%', probability: 0.4202 },
            { option_name: '최대 MP +5%', probability: 0.4202 },
            { option_name: '공격력 +6%', probability: 0.2801 },
            { option_name: '마력 +6%', probability: 0.2801 },
            { option_name: '크리티컬 확률 +6%', probability: 0.1401 },
            { option_name: 'STR +6%', probability: 0.4202 },
            { option_name: 'DEX +6%', probability: 0.4202 },
            { option_name: 'INT +6%', probability: 0.4202 },
            { option_name: 'LUK +6%', probability: 0.4202 },
            { option_name: '데미지 +6%', probability: 0.1401 },
            { option_name: '올스탯 +3%', probability: 0.2801 },
            { option_name: '공격 시 3% 확률로 53의 HP 회복', probability: 0.4202 },
            { option_name: '공격 시 3% 확률로 53의 MP 회복', probability: 0.4202 },
            { option_name: '몬스터 방어율 무시 +3%', probability: 0.2801 },
        ]
    }
];
