// ================================================================
// 에디셔널 유니크 등급 - 무기 (120~200) 잠재능력 옵션
// ================================================================

import { AdditionalPotentialOptionPool } from './types';

export const ADDITIONAL_UNIQUE_WEAPON_120_200: AdditionalPotentialOptionPool[] = [
    // 첫 번째 줄
    {
        potential_grade: '유니크',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 1,
        options: [
            { option_name: '최대 HP +8%', probability: 6.9767 },
            { option_name: '최대 MP +8%', probability: 6.9767 },
            { option_name: '공격력 +9%', probability: 4.6512 },
            { option_name: '마력 +9%', probability: 4.6512 },
            { option_name: '크리티컬 확률 +9%', probability: 4.6512 },
            { option_name: 'STR +9%', probability: 6.9767 },
            { option_name: 'DEX +9%', probability: 6.9767 },
            { option_name: 'INT +9%', probability: 6.9767 },
            { option_name: 'LUK +9%', probability: 6.9767 },
            { option_name: '데미지 +9%', probability: 2.3256 },
            { option_name: '올스탯 +6%', probability: 4.6512 },
            { option_name: '캐릭터 기준 9레벨 당 STR +1', probability: 4.6512 },
            { option_name: '캐릭터 기준 9레벨 당 DEX +1', probability: 4.6512 },
            { option_name: '캐릭터 기준 9레벨 당 INT +1', probability: 4.6512 },
            { option_name: '캐릭터 기준 9레벨 당 LUK +1', probability: 4.6512 },
            { option_name: '공격 시 15% 확률로 95의 HP 회복', probability: 6.9767 },
            { option_name: '공격 시 15% 확률로 95의 MP 회복', probability: 6.9767 },
            { option_name: '몬스터 방어율 무시 +4%', probability: 2.3256 },
            { option_name: '보스 몬스터 데미지 +12%', probability: 2.3256 },
        ]
    },
    // 두 번째 줄
    {
        potential_grade: '유니크',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 2,
        options: [
            { option_name: '최대 HP +5%', probability: 8.6505 },
            { option_name: '최대 MP +5%', probability: 8.6505 },
            { option_name: '공격력 +6%', probability: 5.7670 },
            { option_name: '마력 +6%', probability: 5.7670 },
            { option_name: '크리티컬 확률 +6%', probability: 2.8835 },
            { option_name: 'STR +6%', probability: 8.6505 },
            { option_name: 'DEX +6%', probability: 8.6505 },
            { option_name: 'INT +6%', probability: 8.6505 },
            { option_name: 'LUK +6%', probability: 8.6505 },
            { option_name: '데미지 +6%', probability: 2.8835 },
            { option_name: '올스탯 +3%', probability: 5.7670 },
            { option_name: '공격 시 3% 확률로 53의 HP 회복', probability: 8.6505 },
            { option_name: '공격 시 3% 확률로 53의 MP 회복', probability: 8.6505 },
            { option_name: '몬스터 방어율 무시 +3%', probability: 5.7670 },
            { option_name: '최대 HP +8%', probability: 0.1368 },
            { option_name: '최대 MP +8%', probability: 0.1368 },
            { option_name: '공격력 +9%', probability: 0.09120 },
            { option_name: '마력 +9%', probability: 0.09120 },
            { option_name: '크리티컬 확률 +9%', probability: 0.09120 },
            { option_name: 'STR +9%', probability: 0.1368 },
            { option_name: 'DEX +9%', probability: 0.1368 },
            { option_name: 'INT +9%', probability: 0.1368 },
            { option_name: 'LUK +9%', probability: 0.1368 },
            { option_name: '데미지 +9%', probability: 0.04560 },
            { option_name: '올스탯 +6%', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 STR +1', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 DEX +1', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 INT +1', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 LUK +1', probability: 0.09120 },
            { option_name: '공격 시 15% 확률로 95의 HP 회복', probability: 0.1368 },
            { option_name: '공격 시 15% 확률로 95의 MP 회복', probability: 0.1368 },
            { option_name: '몬스터 방어율 무시 +4%', probability: 0.04560 },
            { option_name: '보스 몬스터 데미지 +12%', probability: 0.04560 },
        ]
    },
    // 세 번째 줄
    {
        potential_grade: '유니크',
        equipment_type: '무기',
        level_range: '120~200',
        line_position: 3,
        options: [
            { option_name: '최대 HP +5%', probability: 8.6505 },
            { option_name: '최대 MP +5%', probability: 8.6505 },
            { option_name: '공격력 +6%', probability: 5.7670 },
            { option_name: '마력 +6%', probability: 5.7670 },
            { option_name: '크리티컬 확률 +6%', probability: 2.8835 },
            { option_name: 'STR +6%', probability: 8.6505 },
            { option_name: 'DEX +6%', probability: 8.6505 },
            { option_name: 'INT +6%', probability: 8.6505 },
            { option_name: 'LUK +6%', probability: 8.6505 },
            { option_name: '데미지 +6%', probability: 2.8835 },
            { option_name: '올스탯 +3%', probability: 5.7670 },
            { option_name: '공격 시 3% 확률로 53의 HP 회복', probability: 8.6505 },
            { option_name: '공격 시 3% 확률로 53의 MP 회복', probability: 8.6505 },
            { option_name: '몬스터 방어율 무시 +3%', probability: 5.7670 },
            { option_name: '최대 HP +8%', probability: 0.1368 },
            { option_name: '최대 MP +8%', probability: 0.1368 },
            { option_name: '공격력 +9%', probability: 0.09120 },
            { option_name: '마력 +9%', probability: 0.09120 },
            { option_name: '크리티컬 확률 +9%', probability: 0.09120 },
            { option_name: 'STR +9%', probability: 0.1368 },
            { option_name: 'DEX +9%', probability: 0.1368 },
            { option_name: 'INT +9%', probability: 0.1368 },
            { option_name: 'LUK +9%', probability: 0.1368 },
            { option_name: '데미지 +9%', probability: 0.04560 },
            { option_name: '올스탯 +6%', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 STR +1', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 DEX +1', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 INT +1', probability: 0.09120 },
            { option_name: '캐릭터 기준 9레벨 당 LUK +1', probability: 0.09120 },
            { option_name: '공격 시 15% 확률로 95의 HP 회복', probability: 0.1368 },
            { option_name: '공격 시 15% 확률로 95의 MP 회복', probability: 0.1368 },
            { option_name: '몬스터 방어율 무시 +4%', probability: 0.04560 },
            { option_name: '보스 몬스터 데미지 +12%', probability: 0.04560 },
        ]
    }
];
